### ISSUE TITLE
Unable to install with vue-router@^4.0.12

### ISSUE THREAD

**Issue by naviisml** [vuejs/vuex-router-sync#105]
As the title describes, I'm unable to install vuex-router-sync with vue-router@^4.0.12. I can provider the full logs, but it seems unnecessary as the it is fairly straight forward.

**Comment by cuebit** [comment]
@naviisml did you install the compatible version? i.e. `npm install vuex-router-sync@next`

**Comment by naviisml** [comment]
Dumb me, this solved the issue.

I do recommend putting it in the readme tho, as it states:
```
# the latest version works only with vue-router >= 2.0
npm install vuex-router-sync
```
