### ISSUE TITLE
How to update route state with own mutation, action and splited store?

### ISSUE THREAD

**Issue by cve** [vuejs/vuex-router-sync#12]
Hi,

first of all big thanks for such great framework :).

I'm building data-table-grid like app, and I have some basic sort of "filtering" functionality with text inputs, and I want to sync it's values with query params in route? If someone change query param value it should update input text filter for that, and on the other hand if I update the input it should save it's updated state in the query param.

How to achieve that?

I'm playing with https://github.com/skyronic/vue-spa example app which has splited modules like cart and products, but vuex-router-sync adds its own route module... I dont know how can I supply my "route store" with my own "actions" and "mutations" for update that filter state in change in url and "getters"

There is so many files in that project, I want to provide a live example for you with, but in http://www.webpackbin.com/ I have so errors with file paths...

**Comment by chrisvfritz** [comment]
@cve Glad to hear you're enjoying Vue. 😄  Since this is neither a bug nor a feature request though, I recommend posting your question on either [the forum](http://forum.vuejs.org/) or [the Gitter chat](https://gitter.im/vuejs/vue).
