### ISSUE TITLE
Incompatable with vuex 0.8.0

### ISSUE THREAD

**Issue by nblackburn** [vuejs/vuex-router-sync#17]
I have recently updated my application to use vuex 0.8.0 which seems to cause infinite redirects when used in conjunction with router-sync.

**Comment by khozzy** [comment]
I confirm, works well on 0.6.2

**Comment by chrisvfritz** [comment]
I recommend holding off an upgrade until the release of 2.0, as vuex and some other libraries are going through some very active development including breaking changes in preparation for it.

**Comment by nblackburn** [comment]
@chrisvfritz I don't really depend on router-sync so disabling it works fine for the time being. That being said, you are right despite @yyx990803 trying to maintain compatibility both both at the moment.

**Comment by transtone** [comment]
It can't work with 0.8.2

**Comment by zack24q** [comment]
+1,
0.8.2 will throw a error "Uncaught TypeError: Cannot set property 'path' of undefined". at this line [https://github.com/vuejs/vuex-router-sync/blob/master/index.js#L56](url)

**Comment by yyx990803** [comment]
Fixed in 1.0.1
