### ISSUE TITLE
npm install vuex-router-sync@next 3.0.0 invalid

### ISSUE THREAD

**Issue by judocode** [vuejs/vuex-router-sync#24]
When attempting to run `npm install vuex-router-sync@next` I get the error `-- vuex-router-sync@3.0.0  invalid`.

**Comment by willishq** [comment]
I just ran this and didn't receive this error.

**Comment by fnlctrl** [comment]
Cannot reproduce here... @jrenton  Can you give us a screenshot?

**Comment by judocode** [comment]
@willishq @fnlctrl It seems to work now. It must have been a temporary error.
