### ISSUE TITLE
Uncaught TypeError: Cannot read property 'path' of undefined

### ISSUE THREAD

**Issue by peirancao** [vuejs/vuex-router-sync#25]
```
"vue": "^2.0.1",
"vue-router": "^2.0.0",
"vuex": "^2.0.0",
"vuex-router-sync": "^3.0.0"
```

routes

```
const routes = [
  {
    path: '/',
    component: Home
  },
  {
    path: '/about',
    component: About
  }
]
```

has error

```
import { sync } from 'vuex-router-sync'
import router from './router'
import store from './store'

sync(store, router)
```

no error

```
// import { sync } from 'vuex-router-sync'
import router from './router'
import store from './store'

// sync(store, router)
```

**Comment by xmoki** [comment]
make sure you install vuex-router-sync@3.0.0 and not 2.x
i had the same problem with 2.x, when i installed 3.0.0 got no errors

**Comment by smallpath** [comment]
The doc should be updated since there isn't a @next branch available on npm now

**Comment by crswll** [comment]
@Smallpath The README.md says it. I just totally overlooked it. It was last updated 3 months ago so it must have been in there a while. I think this is good to close.

**Comment by stephenzhao** [comment]
[Uncaught TypeError: Cannot read property 'route' of undefined ]  when i installed 3.0.0

**Comment by yyx990803** [comment]
The default install is now compatible with vue-router and vuex 2.x. If there are still errors with the latest version, please open a separate issue.

**Comment by cuduy197** [comment]
`Uncaught TypeError: Cannot read property 'path' of undefined ` 
  "vuex-router-sync": "^4.1.2"
 "vue": "^2.2.2",
 "vue-router": "^2.3.0",

**Comment by krns** [comment]
Same for me
```
"vue": "^2.2.6",
"vue-router": "^2.4.0",
"vuex-router-sync": "^4.1.2"
```

**Comment by LinusBorg** [comment]
> please open a separate issue.

....

**Comment by K69G4JRA725W** [comment]
"vue": "^2.3.4",
"vue-router": "^2.5.3",
"vuex-router-sync": "^4.1.2"

[vue-router] uncaught error during route navigation:
TypeError: Cannot read property 'path' of undefined

**Comment by LinusBorg** [comment]
I won't repeat my request a third time. Locking this now.
