### ISSUE TITLE
Cannot read property 'route' of undefined

### ISSUE THREAD

**Issue by nqdy666** [vuejs/vuex-router-sync#27]
When I use vuex-router-sync, but something wrong happened

```
import { sync } from 'vuex-router-sync'
import router from './router'
import store from './store'
sync(store, router)
```

error message

```
Uncaught TypeError: Cannot read property 'route' of undefined            index.js:23
```

dependencies

```
    "vue": "^2.0.1",
    "vue-router": "2.0.0-rc.5",
    "vuex": "^2.0.0",
    "vuex-router-sync": "^3.0.0"
```

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue. Please follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) and provide a live reproduction on jsfiddle, codepen etc. Thanks!

**Comment by shhdgit** [comment]
@nqdy666 Maybe you use wrong property(vuex) in instance.
vuex2.0 use mapState() function instead getters.
http://vuex.vuejs.org/en/state.html

**Comment by zcfan** [comment]
@nqdy666 Already "fixed" in 21a6838e39b005aa15e98dc264110a973d602b9a , try install the 3.0.0 version `npm i -S vuex-router-sync@3.0.0`

**Comment by luckyufei** [comment]
@nqdy666  this problem happen because you have this line `store.replaceState(window.__INITIAL_STATE__)` in not server render mode.

**Comment by yyx990803** [comment]
Assuming the previous comment resolved the issue - please reopen if that's not the case.

**Comment by wong2** [comment]
I solved this by:

```
if (window.__INITIAL_STATE__) {
  store.replaceState(window.__INITIAL_STATE__)
}
```
