### ISSUE TITLE
need fetch "from" state not just the "to" state

### ISSUE THREAD

**Issue by zppro** [vuejs/vuex-router-sync#29]
i think it's necessary to add get from state info like `beforeRouteEnter (from,to,next)` now we can fetch the to state by store.route but some times to a  view  we must decide wether or not load data by the from state's path.
i.e. go to a product-details view from `product-list view` need loading details info and in that `product-details view` go to anther `order view` and back ,some contents managed by `vuex` had changed,so in details view i don't want load data because not necessary)

**Comment by predhme** [comment]
#36 Is a proposed changed to support storing the `from` transition in `state.route`

**Comment by yyx990803** [comment]
done by merging #36, now out in 4.0
