### ISSUE TITLE
Hold a reference to the router object?

### ISSUE THREAD

**Issue by Garmichael** [vuejs/vuex-router-sync#30]
I have a need to redirect the user after a store action, but the store doesn't have access to the router object itself. 

I forked it locally and added a reference in the `store.registerModule`:

```
  store.registerModule('route', {
    state: {},
    mutations: {
      'router/ROUTE_CHANGED': function (state, to) {
        store.state.route = Object.freeze({
          name: to.name,
          path: to.path,
          hash: to.hash,
          query: to.query,
          params: to.params,
          fullPath: to.fullPath,
          router: router
        })
      }
    }
  })
```

Can this be made official? Or is there a good reason not to be have access to the router in the store that I'm not aware of?

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue. You can directly import/require the router instance to get the reference, there's no need to inject it into the store.

**Comment by lambdalisue** [comment]
I like this idea as well. Is there any chance to re-disscuss?

For example, if a router instance is created and assigned to Vue instance in a function, we cannot access the router instance by require/import.
