### ISSUE TITLE
there is no meta info in route.

### ISSUE THREAD

**Issue by Sloaix** [vuejs/vuex-router-sync#31]
there is no meta info in route.only path,params,query.

so i can't get the meta info in store.

**Comment by yyx990803** [comment]
router 2.0 route meta is not directly exposed. You need to check `route.matched.forEach(r => r.meta)`: http://router.vuejs.org/en/advanced/meta.html

**Comment by wolthers** [comment]
@yyx990803 Matched isn't exposed on store, so checking `matched` is only possible in a guard, which is not always what you want. There's an open PR on this: https://github.com/vuejs/vuex-router-sync/pull/32
