### ISSUE TITLE
$router.push doesn't change the URL

### ISSUE THREAD

**Issue by quangv** [vuejs/vuex-router-sync#53]
`router.push` and `this.$router.push` does not changes the URL when using _vuex-router-sync_.

`<router-link>` works as expected.

When I remove _vuex-router-sync_ `router.push` works as expected.

```
// current url #/foo
this.$router.push({path: 'bar'})
// expects URL to be #/bar
// actual URL is still #/foo
```

**Comment by wojtiku** [comment]
Hey @quangv,
Could you give more details? A reproducible jsfiddle or something maybe? I just tried to do this with newest versions of all libraries and it works like a charm. Is it possible that this has been fixed already?
Cheers,
Wojtek

**Comment by quangv** [comment]
There code base I was working with wasn't so great and I suspect I just had the signature of the call or name of path wrong. 

Thanks. Closing now.

**Comment by quangv** [comment]
If I come across it again I'll re-open ticket.
