### ISSUE TITLE
Getters for route params

### ISSUE THREAD

**Issue by existe-deja** [vuejs/vuex-router-sync#54]
Is there a way to have `getters` for the `route` params/query instead of `rootState.route`?

**Comment by psycokenisis** [comment]
Its not documented, but they are there; `getters.routeQueryParams` and `getters.routeParams`.
If you're using the [VueJS devtool extension](https://github.com/vuejs/vue-devtools), you'll be able to see the whole vuex state and getters. It helps a lot in general, and I accidentally discovered those two, which weren't documented in the `README.md`

**Comment by psycokenisis** [comment]
*edit* I deleted my previous comment about `vuex-router-sync` having the getters. Turns out I was silly and added the getters myself and completely forgot about it...

I put this at the top of my `vuex` store and it makes life easier and as easily accessible as the global route state when in other modules.
```
  getters: {
    routeQueryParams: (state, allGetters, rootState) => rootState.route.query,
    routeParams: (state, allGetters, rootState) => rootState.route.params,
  },
```

**Comment by chasebank** [comment]
@psycokenisis Awesome... is there any way to then reference `routeParams` inside another getter? Or am I better off just following the same pattern in the other getter, to target the route param again?

**Comment by danieldiekmeier** [comment]
@chasebank Every other getter is available via the `allGetters` parameter. So you could do this:

```js
getters: {
  routeQueryParams: (state, allGetters, rootState) => rootState.route.query,
  routeParams: (state, allGetters, rootState) => rootState.route.params,

  yourGetter: (state, allGetters) => allGetters.routeParams.yourParam
}
```

See also here (at "getters"): https://vuex.vuejs.org/en/api.html#vuexstore-constructor-options

**Comment by robokozo** [comment]
I made a post here: https://github.com/vuejs/vuex-router-sync/issues/68#issuecomment-331238566

Basically, by naming a custom module the same as the sync module ('route' by default) you can have getters existing in the same module as your route state properties.

**Comment by posva** [comment]
I see this hasn't been updated in a very long time. You can access params directly from the `route` with `route.params`. If you prefer adding a getter `routeParams`, you can always add it yourself but using `route.params` or `routeParams` is just personal preference
