### ISSUE TITLE
newly added module properties aren't reactive

### ISSUE THREAD

**Issue by mtpc** [vuejs/vuex-router-sync#55]
I understand the need for immutability expressed here by cloning then freezing the route object,
but it prevents Vue from making the properties observable, which means getters depending on the route module state are not cached like standard computed properties and recompute every time the route object changes, even if some properties (params, query) stay the same.

I resolved this in my project by making my own sync module which diffs the old route object with the new one, but I assume this may be a concern for more people in the future.

**Comment by posva** [comment]
Seeing this now. Properties are only copied, do you have a more concrete example of what you're trying to do? or a repro?

**Comment by mtpc** [comment]
This issue is so old I'm not even sure this applies anymore. I'll check it, but feel free to close it until additional informations.

**Comment by posva** [comment]
Ok, thanks for the quick answer 👍
