### ISSUE TITLE
Support to namespace feature?

### ISSUE THREAD

**Issue by ciceropablo** [vuejs/vuex-router-sync#58]
Something about it?

**Comment by posva** [comment]
Can you give more details, please?

**Comment by ciceropablo** [comment]
Something like that:
```js
...mapState('RouterModule', {
  foo: state => state.params.foo,
  bar: state => state.params.bar,
  baz: state => state.params.baz,
});
```

Instead of:
```js
...mapState({
  foo: state => state.RouterModule.params.foo,
  bar: state => state.RouterModule.params.bar,
  baz: state => state.RouterModule.params.baz,
});
```

**Comment by posva** [comment]
You can already do:

```js
...mapState('route', {
  foo: state => state.params.foo,
  bar: state => state.params.bar,
  baz: state => state.params.baz,
});
```

**Comment by ciceropablo** [comment]
My log message:
```
[vuex] module namespace not found in mapState(): route/
```

**Comment by LinusBorg** [comment]
1. What does that have to do with vuex-router-sync? this seems to be related to vuex only.
2. Which version of vuex are you using? @posva's way works with uptodate versions of vuex.
3. If it doesn't work for you, please provide a proper reporduction.

**Comment by posva** [comment]
yeah, he should have provided a repro but turns out it's not easy at all to do it because the file only works with a bundler. Here's a repro: https://jsfiddle.net/oq8aLt0y/

**Comment by LinusBorg** [comment]
Ah, now I understand what he means, thanks.

This would be abreaking change as it would be incopatible with vuex 2.0.0 -namespacing came later.

**Comment by posva** [comment]
I'm still confused, I think it should work xD

**Comment by mlanin** [comment]
Same here. May be the reason is that module is not namespaced at all? As far as I can see in docs, in order to make module namespaced, it should have `namespaced: true` attribute and route module doesn't have it.

**Comment by yyx990803** [comment]
4.2.0 now registers the route module with `namespaced: true`.

**Comment by mlanin** [comment]
@yyx990803 thanks! When it will be released?

**Comment by yyx990803** [comment]
@mlanin it's now out :)
