### ISSUE TITLE
currentPath should has a init value

### ISSUE THREAD

**Issue by xiachaoxulu** [vuejs/vuex-router-sync#59]
currentPath is undefined

server Rending ...
 store.replaceState(window.__INITIAL_STATE__)   

since currentPath is undefined , so router.push(route) must be excute.  the history must has two record

**Comment by xiachaoxulu** [comment]
see already has a pr.  i think more， when currentPath is undefined ,router should replace 。
because currentPath init value should be from server

**Comment by yyx990803** [comment]
Closed via #52
