### ISSUE TITLE
使用vuex-router-sync后，在beforeResolve中调用vuex里registerModule会再次触发beforeResolve回调

### ISSUE THREAD

**Issue by 525729985** [vuejs/vuex-router-sync#60]
使用vuex-router-sync后，在beforeResolve中调用vuex里registerModule会再次触发beforeResolve回调,结果导致页面数据读取两次。
//package.json
    "vue": "^2.2.1",
    "vue-router": "^2.5.3",
    "vuex": "^2.3.1",
    "vuex-router-sync": "^4.1.3"
//js
router.beforeResolve((to, from, next) => {
    store.registerModule("test" , {});
    console.log(to)
    next();
  });
//console
Object { name: undefined, meta: Object, path: "/home", hash: "", query: Object, params: Object, fullPath: "/home", matched: Array[1], redirectedFrom: "/" }
Object { name: undefined, meta: Object, path: "/home", hash: "", query: Object, params: Object, fullPath: "/home", matched: Array[1] }

**Comment by yyx990803** [comment]
`beforeResolve` 每次路由跳转都会被调用的，为什么会在这里面注册 vuex 模块？不太能理解这种用法。

**Comment by 525729985** [comment]
想法是进页面的时候挂上module，离开页面的时候卸掉，觉得对网页来说每次进都要重新加载数据那些module留着意义不大。

**Comment by yyx990803** [comment]
建议在组件的生命周期而不是路由钩子里做这件事。

**Comment by guojingwen** [comment]
@yyx990803 
在生命周期里 store.registerModule SPA是可以的，
但是ssr 怎么做？
