### ISSUE TITLE
Performance with vuex `encode`

### ISSUE THREAD

**Issue by jackysee** [vuejs/vuex-router-sync#65]
Noticing a reported click delay in console, I tried to get a flame chart of the click actions. The result shows that it takes most of its time in a vuex `encode` method. When I tried to debug, it is encoding the router object, which has some deeply nested components structure like `data.from.matched[0].instances.default.$children[0].$children[0].$children[0].....`.  I haven't dived into what `encode` is doing but wonder if it is necessary?

![vuex-router-sync-encode](https://user-images.githubusercontent.com/30516/28805521-3ae524f0-769d-11e7-82da-9116da62c16c.png)

![vuex-router-sync-encode-debug](https://user-images.githubusercontent.com/30516/28805582-bc22a10a-769d-11e7-9f55-216f029a5522.png)

**Comment by yyx990803** [comment]
This is from the devtools (when sending Vuex snapshots). It seems you are putting a route object into your component's data which leads to this behavior - this may need some special treatment in the devtools, but in the meanwhile you can either avoid doing that, or turn off vuex recording in the devtools (click the red button)

**Comment by jackysee** [comment]
Thanks, it's much better after turning off the devtool vuex recording.
