### ISSUE TITLE
a question of `vuex-router-sync`

### ISSUE THREAD

**Issue by langgo** [vuejs/vuex-router-sync#67]
I don't know much about the usage scenario of `vuex-router-sync`.  What problem is it mainly used to solve? ( In other words, after using the router in vuex, you can solve a problem very easy )

我不太清楚 vuex-router-sync 的应用场景。它主要是用来解决什么问题。（换句话说，在使用了 router in vuex 之后，可以很好的解决某类问题）。

thx.
谢谢

**Comment by posva** [comment]
It gives you access to the `$route` in vuex because it adds it to the state

**Comment by langgo** [comment]
Your answer is cheap.
