### ISSUE TITLE
4.3.0 broken in IE10 because of "const" statement

### ISSUE THREAD

**Issue by marcoeh** [vuejs/vuex-router-sync#69]
A stray const statement killed our build in IE10. This seems to have happened because the wrong version got into the dist of the version 4.3.0.
See the top comment in the distributed file: https://cdn.jsdelivr.net/npm/vuex-router-sync@4.3.0/index.min.js

```javascript
/**
 * Failed to minify the file using UglifyJS v3.0.24. Serving the original version.
```

Thanks for looking into it.

**Comment by MartinKolarik** [comment]
FYI, the comment is added by jsDelivr - [the package only contains unminified file](https://www.jsdelivr.com/package/npm/vuex-router-sync), so jsDelivr attempts to minify it but fails because of the `const` statement.

**Comment by marcoeh** [comment]
In that case I'm guessing backwards compatibility is not a priority? @yyx990803

**Comment by MartinKolarik** [comment]
Wow, that was a fast fix 👍  @marcoeh check https://cdn.jsdelivr.net/npm/vuex-router-sync@4.3.1/index.min.js

**Comment by marcoeh** [comment]
🎉 Yeah! Thank's 👍 🏅
