### ISSUE TITLE
Route error: Cannot read property 'push' of undefined

### ISSUE THREAD

**Issue by k-slash** [vuejs/vuex-router-sync#74]
Hi,
Is it possible to use route in vuex action ?
I also tried in component but it doesn't work too. I have this error: 'Cannot read property 'push' of undefined'
Here is a jsfiddle example of what I would like to do: https://jsfiddle.net/ndqchq4s/1/
Error on line 126

Thanks

**Comment by posva** [comment]
You have to import the router at the top of your actions.js file to use it

**Comment by k-slash** [comment]
Still doesn't work.
Did you read my code on jsfiddle ?
And if you are so sure of your answer to close the issue, can you show me an example that works ?
Thanks

**Comment by posva** [comment]
It does work and yes, I did read.
I'm closing the issue because it's a question and we use the [forum](http://forum.vuejs.org/) and the [Discord server](https://vue-land.js.org/) for that purpose

I didn't add the code because it's just this

```js
import router from './router'

router.push('/path')
```

You can do `router.push` anywhere

**Comment by k-slash** [comment]
Ok, thanks for your quick answer. I'll ask my question on the forum or on discord.
When I said an example, I mean a project which use router on vuex action.
But nevermind, I'll check the forum. 
Thank you

**Comment by k-slash** [comment]
I resolved my issue, actually my problem was due to beforeEnter function in my router file.
By the way, for those who read my comment, use codesandbox.io instead of jsfiddle, it's more appropriated for Vue projects.

**Comment by matheus-rossi** [comment]
@k-slash what did you do ?
same issue here ...

**Comment by k-slash** [comment]
If I remember correctly, my problem was due to the beforeEnter function. 
You can find an example that works here : https://codesandbox.io/s/ppqwr4rrkx
If you still have a problem, show me an example on codesandbox.io or jsfiddle so I can see where is the problem.

**Comment by k-slash** [comment]
To respond to you @matheus-rossi
