### ISSUE TITLE
Route param sync issue with vue-router 3.0.0, vuex 3.0.0 and vuex-router-sync 5.0.0

### ISSUE THREAD

**Issue by michaelhunziker** [vuejs/vuex-router-sync#76]
Hi all!

There seems to be a route state sync issue with the current vue-router, vuex and vuex-router-sync version.

I get an empty object for state.route.params within my getter function using the following versions:
`
"vue": "^2.4.2",
"vue-router": "^3.0.0",
"vuex": "^3.0.0",
"vuex-router-sync": "^5.0.0"
`

The statement state.route.params used to return the correct state params (for the current route) using the following versions:
`
"vue": "^2.4.2", 
"vue-router": "2.7.0",
"vuex": "2.4.1",
"vuex-router-sync": "4.3.2"
`

Michael

**Comment by yyx990803** [comment]
Please provide a reproduction if possible.

**Comment by michaelhunziker** [comment]
Working example:
"vue": "^2.4.2", "vue-router": "2.7.0", "vuex": "2.4.1", "vuex-router-sync": "4.3.2"
https://codepen.io/michaelhunziker/pen/GMBGpB

Not working:
"vue": "^2.4.2", "vue-router": "^3.0.0", "vuex": "^3.0.0", "vuex-router-sync": "^5.0.0"
https://codepen.io/michaelhunziker/pen/gGdbZv


p.s. I couldn't find a CDN version to include within the codepen thus i had to inline vuex-router-sync. Is there a way to include vuex-router-sync with CDN?

**Comment by yyx990803** [comment]
FYI this is a regression in `vue-router` and will be fixed with a patch release soon.

**Comment by neves** [comment]
I'm having the same problem, any update on this issue?

**Comment by jeissler** [comment]
@yyx990803 I'm also wondering what the progress is on this as I'm facing a similar issue? In my case multiple query string params `?foo=bar&bar=foo` cause vuex-router-sync to not return the correct route params for the next route where just `?foo=bar` does not. What's even more interesting is this is only happening when our app is deployed to aws lambda and isn't reproducible locally in development or w/ serverless offline :(
