### ISSUE TITLE
TypeError: o is null

### ISSUE THREAD

**Issue by imadHafsi** [vuejs/vuex-router-sync#78]
after using this : sync(store,router);

when i click on every route  : 

[vue-router] uncaught error during route navigation:
vue-router.esm.js:16
TypeError: o is null
Stack trace:
x/<@moz-extension://b286394e-ceba-46c9-a658-f2b70ed3a055/build/backend.js:1:18633
x@moz-extension://b286394e-ceba-46c9-a658-f2b70ed3a055/build/backend.js:1:18295
[6]/t.a@moz-extension://b286394e-ceba-46c9-a658-f2b70ed3a055/build/backend.js:1:14243
y@moz-extension://b286394e-ceba-46c9-a658-f2b70ed3a055/build/backend.js:1:1916
e@moz-extension://b286394e-ceba-46c9-a658-f2b70ed3a055/build/backend.js:1:5817
e@moz-extension://b286394e-ceba-46c9-a658-f2b70ed3a055/build/backend.js:1:5837
e@moz-extension://b286394e-ceba-46c9-a658-f2b70ed3a055/build/backend.js:1:5837
e@moz-extension://b286394e-ceba-46c9-a658-f2b70ed3a055/build/backend.js:1:5837
e@moz-extension://b286394e-ceba-46c9-a658-f2b70ed3a055/build/backend.js:1:5837
e@moz-extension://b286394e-ceba-46c9-a658-f2b70ed3a055/build/backend.js:1:5837
e@moz-extension://b286394e-ceba-46c9-a658-f2b70ed3a055/build/backend.js:1:5959
e@moz-extension://b286394e-ceba-46c9-a658-f2b70ed3a055/build/backend.js:1:5837
e@moz-extension://b286394e-ceba-46c9-a658-f2b70ed3a055/build/backend.js:1:5837
[12]/t.stringifyStrict@moz-extension://b286394e-ceba-46c9-a658-f2b70ed3a055/build/backend.js:1:5645
[12]/t.stringify@moz-extension://b286394e-ceba-46c9-a658-f2b70ed3a055/build/backend.js:1:5173
[0]/t.o@moz-extension://b286394e-ceba-46c9-a658-f2b70ed3a055/build/backend.js:1:662
[14]/t.a/<@moz-extension://b286394e-ceba-46c9-a658-f2b70ed3a055/build/backend.js:1:7444
emit@http://localhost:8080/#/:1:469
devtoolPlugin/<@webpack-internal:///./node_modules/vuex/dist/vuex.esm.js:65:5
commit/<@webpack-internal:///./node_modules/vuex/dist/vuex.esm.js:399:53
commit@webpack-internal:///./node_modules/vuex/dist/vuex.esm.js:399:3
boundCommit@webpack-internal:///./node_modules/vuex/dist/vuex.esm.js:342:12
exports.sync/afterEachUnHook<@webpack-internal:///./node_modules/vuex-router-sync/index.js:41:5
updateRoute/<@webpack-internal:///./node_modules/vue-router/dist/vue-router.esm.js:1999:13
updateRoute@webpack-internal:///./node_modules/vue-router/dist/vue-router.esm.js:1998:3
transitionTo/<@webpack-internal:///./node_modules/vue-router/dist/vue-router.esm.js:1875:5
confirmTransition/</<@webpack-internal:///./node_modules/vue-router/dist/vue-router.esm.js:1984:7
step@webpack-internal:///./node_modules/vue-router/dist/vue-router.esm.js:1714:7
step@webpack-internal:///./node_modules/vue-router/dist/vue-router.esm.js:1721:9
runQueue@webpack-internal:///./node_modules/vue-router/dist/vue-router.esm.js:1725:3
confirmTransition/<@webpack-internal:///./node_modules/vue-router/dist/vue-router.esm.js:1979:5
step@webpack-internal:///./node_modules/vue-router/dist/vue-router.esm.js:1714:7
step/<@webpack-internal:///./node_modules/vue-router/dist/vue-router.esm.js:1718:11
iterator/<@webpack-internal:///./node_modules/vue-router/dist/vue-router.esm.js:1964:11
resolveAsyncComponents/<@webpack-internal:///./node_modules/vue-router/dist/vue-router.esm.js:1792:22
iterator@webpack-internal:///./node_modules/vue-router/dist/vue-router.esm.js:1943:7
step@webpack-internal:///./node_modules/vue-router/dist/vue-router.esm.js:1717:9
step@webpack-internal:///./node_modules/vue-router/dist/vue-router.esm.js:1721:9
step@webpack-internal:///./node_modules/vue-router/dist/vue-router.esm.js:1721:9
runQueue@webpack-internal:///./node_modules/vue-router/dist/vue-router.esm.js:1725:3
confirmTransition@webpack-internal:///./node_modules/vue-router/dist/vue-router.esm.js:1972:3
transitionTo@webpack-internal:///./node_modules/vue-router/dist/vue-router.esm.js:1874:3
push@webpack-internal:///./node_modules/vue-router/dist/vue-router.esm.js:2273:5
push@webpack-internal:///./node_modules/vue-router/dist/vue-router.esm.js:2534:3
handler@webpack-internal:///./node_modules/vue-router/dist/vue-router.esm.js:444:11
invoker@webpack-internal:///./node_modules/vue/dist/vue.esm.js:2003:14
withMacroTask/fn._withTask@webpack-internal:///./node_modules/vue/dist/vue.esm.js:1801:15

**Comment by posva** [comment]
Seems to be a problem from the devtools (https://github.com/vuejs/vue-devtools/issues/499)
If it's not, please, provide a boiled down repro showcasing the bug

**Comment by imadHafsi** [comment]
thank you @posva when i remove vue-devtools it's work perfectly
