### ISSUE TITLE
Store 代码拆分

### ISSUE THREAD

**Issue by guojingwen** [vuejs/vuex-router-sync#79]
按照官网 https://ssr.vuejs.org/zh/data.html  Store 代码拆分(Store Code Splitting)
在asyncData函数里 store.dispatch('foo/inc) OK的
然而在vue生命周期里(比如mounted)调用store.dispatch('foo/inc) 就报错了
[vuex] unknown action type: foo/inc

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
