### ISSUE TITLE
Router path get null

### ISSUE THREAD

**Issue by Hazlank** [vuejs/vuex-router-sync#82]
Why sometimes my router path name is null,but sometimes it can get in actions/mutations function

**Comment by Hazlank** [comment]
"vuex-router-sync": "^5.0.0"
    "vue-router": "^3.0.1",

**Comment by JounQin** [comment]
You need to provide a reproduction please.

**Comment by Hazlank** [comment]
@JounQin 什么意思...
反正不知道为什么有时候刷新页面actions里并不能同步获取到route的信息，比如没有route的name ，path还只是‘/’

**Comment by JounQin** [comment]
……没有提供最小的可重现链接只有简单的文字描述没有任何意义。

**Comment by Hazlank** [comment]
@JounQin .....不是demo，我猜可能是因为我实例化了两个Vue对象的原因....

**Comment by JounQin** [comment]
跟什么 demo 有什么关系……只有文字描述没有可以运行的复现难道别人大海捞针帮你猜吗？提 issue 给重现是基本要求，不然别人帮不上任何忙。

**Comment by yordis** [comment]
Could you provide a demo for be able to reproduce this @Hazlank ? If you don't take the time for provide us a demo we can't help you.

@yyx990803 can we close this? It seems to be stall for a long time.
