### ISSUE TITLE
Cannot synchronize changes from Vue component to Vuex

### ISSUE THREAD

**Issue by MariaSMM** [vuejs/vuex-router-sync#85]
Hey, guys Im newbie in Vuex and I'm trying to understand how it works? I have got some problems with synchronize,
I have got leftsidebar menu and when i change my route, I assume that I can change my Vue.http.get() request, by passing some params from vue-router.
But when im changing my route, my component page doesn't reload, What I need to do??
this is my code:

[test.txt](https://github.com/vuejs/vuex-router-sync/files/2198038/test.txt)

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
