### ISSUE TITLE
Updating the route state after full page refresh

### ISSUE THREAD

**Issue by rudowastaken** [vuejs/vuex-router-sync#9]
Hello, I'm not quite sure if it's caused by misconfiguration on my part (vue webpack template + vue-router + sync), but the `router/ROUTE_CHANGED` mutation is not being called after a full page refresh, resulting in empty route state causing issues when used in combination with derived state. It behaves as expected when browsing the page states afterwards. 

Thanks!

**Comment by bartlomieju** [comment]
I already created PR to fix this: [https://github.com/vuejs/vuex-router-sync/pull/6](https://github.com/vuejs/vuex-router-sync/pull/6).

**Comment by rudowastaken** [comment]
Thank you! I somehow missed that one when I created this issue.

**Comment by JivanRoquet** [comment]
@bartlomieju @HRcc Looks it might be useful to close this issue.
