### ISSUE TITLE
Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by mtdst** [vuejs/vuex-router-sync#90]
+ vue-router@3.0.6
+ vuex-router-sync@5.0.0

```
import { sync } from "vuex-router-sync";

export function createApp() {
  
  sync(store, router)

  const app = new Vue({
    router,
    store,
    render: h => h(App)
  })
  return { app, router, store }
}
```

**Comment by appdrops** [comment]
@mtdst did you find a solution? I have the same issue.

**Comment by guanzo** [comment]
Clearing the vuex localStorage entry fixed it for me 🤷‍♂

**Comment by kiaking** [comment]
Closing due to it seems like about plugin usage.

**Comment by langorbais-git** [comment]
Install the old version of vuex-router-sync.
vuex-router-sync@4.1.0 and vuex-router-sync@4.0.0 work for me.
